export const Users = [
  {
    id: 1,
    profilePicture: "profile1.jfif",
    username: "robert dervcd",
  },
  {
    id: 2,
    profilePicture: "profile2.jfif",
    username: "Mark sucker",
  },
  {
    id: 3,
    profilePicture: "profile3.jfif",
    username: "eqwc qvwy564",
  },
  {
    id: 4,
    profilePicture: "profile4.webp",
    username: "wtrb 5y65 g",
  },
  {
    id: 5,
    profilePicture: "profile5.jfif",
    username: "jhbdcj usvhje",
  },
  {
    id: 6,
    profilePicture: "profile6.jfif",
    username: "wuyg uygiu3i",
  },
  {
    id: 7,
    profilePicture: "profile7.jfif",
    username: "sjvfhj ghvehrj",
  },
  {
    id: 8,
    profilePicture: "profile8.jfif",
    username: "yer ytgrje",
  },
  {
    id: 9,
    profilePicture: "profile9.jfif",
    username: "jwgy kjsh",
  },
  {
    id: 10,
    profilePicture: "profile10.jfif",
    username: "skuygriewu ytey",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love jhegvekj wjhegv",
    photo: "post1.jfif",
    date: "55 mins ago",
    userId: 1,
    like: 22,
    comment: 39,
  },
  {
    id: 2,
    desc: "Love jhegvekj wjhegv",
    photo: "post2.jfif",
    date: "1h  ago",
    userId: 2,
    like: 324,
    comment: 3249,
  },
  {
    id: 3,
    desc: "Love jhegvekj wjhegv",
    photo: "post3.jfif",
    date: "25 mins ago",
    userId: 3,
    like: 92,
    comment: 943,
  },
  {
    id: 4,
    desc: "Love jhegvekj wjhegv",
    photo: "post4.jfif",
    date: "287 mins ago",
    userId: 4,
    like: 46,
    comment: 3494565,
  },
  {
    id: 5,
    desc: "Love jhegvekj wjhegv",
    photo: "post5.jfif",
    date: "2 mins ago",
    userId: 5,
    like: 3342,
    comment: 459,
  },
  {
    id: 6,
    desc: "Love jhegvekj wjhegv",
    photo: "post6.jfif",
    date: "51 mins ago",
    userId: 6,
    like: 33452,
    comment: 543659,
  },
  {
    id: 7,
    desc: "Love jhegvekj wjhegv",
    photo: "post7.jfif",
    date: "5 mins ago",
    userId: 7,
    like: 76,
    comment: 3459,
  },
  {
    id: 8,
    desc: "Love jhegvekj wjhegv",
    photo: "post8.jfif",
    date: "5 mins ago",
    userId: 8,
    like: 2,
    comment: 3249,
  },
  {
    id: 9,
    desc: "Love jhegvekj wjhegv",
    photo: "post9.jfif",
    date: "5 mins ago",
    userId: 9,
    like: 342,
    comment: 9563,
  },
  {
    id: 10,
    desc: "Love jhegvekj wjhegv",
    photo: "post10.jfif",
    date: "5 mins ago",
    userId: 10,
    like: 33742,
    comment: 937,
  },
];
